version: "2"

linters:
  default: all
  disable:
    - godox
    - depguard
    - revive
    - varnamelen

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
    gofumpt:
      extra-rules: true
